// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klrqtalpeudkuotsoaik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscnF0YWxwZXVka3VvdHNvYWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyODE0NzQsImV4cCI6MjA1Mzg1NzQ3NH0.kjrxlWT58g9wIkKdbeiN1ZVDNbk6dsthgQCpzhWBmWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);